branches:
  only:
    - master
    - release
os: windows
language: shell
before_install:
  - choco install python --version=3.7
  - python -m pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests
before_deploy:
  - pyinstaller "build.spec"
  - tar -cf PySpecUI$TRAVIS_BUILD_NUMBER-executable.tar.gz dist\start_ui
  - tar -cf PySpecUI$TRAVIS_BUILD_NUMBER-source.tar.gz peaks
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  skip_cleanup: true
  draft: true
  prerelease: true
  file:
    - PySpecUI$TRAVIS_BUILD_NUMBER-executable.tar.gz
    - PySpecUI$TRAVIS_BUILD_NUMBER-source.tar.gz
  on:
    branch: release
  name: $TRAVIS_TAG (DRAFT)